
talks <- list.files("../talks", full.names=T)
posters <- list.files("../posters", full.names=T)
writeLines(c(
    "\\documentclass[11pt,letterpaper,auto]{article}",
    "\\setlength{\\paperwidth}{16cm}",
    "\\setlength{\\paperheight}{22cm}",
    "\\usepackage{pdfpages}",
    "\\setlength{\\textwidth}{15cm}",
    "\\setlength{\\textheight}{21cm}",
    "\\RequirePackage{ae,mathpple}",
    "\\RequirePackage[T1]{fontenc}",
    "\\renewcommand{\\rmdefault}{ppl}",
    "\\renewcommand{\\sfdefault}{aess}",
    "\\renewcommand{\\ttdefault}{aett}",
    "\\setlength{\\oddsidemargin}{-25mm}",
    "\\setlength{\\evensidemargin}{-25mm}",
    "\\setlength{\\topmargin}{-45mm}",
    "\\setlength{\\headheight}{1cm}",
    "\\setlength{\\headsep}{1cm}",
    "\\parindent = 0em                     ",
    "\\parskip = 1.4ex plus0.1ex minus0ex  ",
    "\\renewcommand{\\baselinestretch}{1.05} ",
    "\\sloppy",
    "\\setlength{\\partopsep}{0mm} \\setlength{\\topsep}{0mm} \\setlength{\\parsep}{0mm}",
    "\\begin{document}",
    "\\pagestyle{empty}",
    "\\clearpage",
             "\\includepdfset{pages=-,pagecommand={\\thispagestyle{empty}},turn=false,noautoscale=false}",
             paste("\\includepdf{talks.pdf}", sep=""),
             paste("\\includepdf{", talks, "}", sep=""),
             paste("\\includepdf{posters.pdf}", sep=""),
             paste("\\includepdf{", posters, "}", sep=""),
    "\\end{document}"),
    con = "_Abstracts1.tex")
library("tools")
texi2dvi("_Abstracts1.tex", pdf = TRUE, clean = TRUE)
writeLines(c(
    "\\documentclass[11pt,letterpaper,twoside,auto]{article}",
    "\\setlength{\\oddsidemargin}{-10mm} ",
    "\\setlength{\\evensidemargin}{-10mm} ",
    "\\setlength{\\topmargin}{-15mm}    ",
    "\\setlength{\\headheight}{1cm}",
    "\\setlength{\\headsep}{1cm}",
    "\\setlength{\\footskip}{1cm} ",
    "\\setlength{\\textwidth}{16cm} ",
    "\\setlength{\\textheight}{21cm} ",
    "\\usepackage{pdfpages}",
    "\\usepackage{fancyhdr}",
    "\\fancyfoot{} % clear all footer fields",
    "\\fancyhead{} % clear all header fields",
    "\\fancyhead[RO,LE]{\\thepage}",
    "\\fancyhead[LO,RE]{\\slshape useR! 2014, Los Angeles, USA}",
    "\\begin{document}",
    "\\pagestyle{empty}",
    "\\includepdfset{pages=-,pagecommand={},turn=false,noautoscale=true}",
    "\\includepdf[pagecommand={\\thispagestyle{empty}}]{cover.pdf}",
    "\\cleardoublepage",
    "\\pagestyle{fancy}",
    "\\setcounter{page}{1}",
    "\\includepdf{_Abstracts1.pdf}",
    "\\end{document}"),
    con = "Abstracts.tex")
texi2dvi("Abstracts.tex", pdf = TRUE, clean = TRUE)

